### ISSUE TITLE
DTMF AND video

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [fonoster/wphone#1]
Hi!
is wphone support DTMF (inbound? rfc2880? sipinfo?)
and video?
thanks

**Comment by psanders** [comment]
Hi @ROBERT-MCDOWELL,

The wphone is a wrapper for SIP.js. 

So it does supports both [DTMF RFC 2833 or SIP INFO.](https://github.com/onsip/SIP.js/tree/2e1c525279c8d6deebb6ecaf3d14477ab7b63310#sip-library-for-javascript)

I'm closing this as resolved.

**Comment by ROBERT-MCDOWELL** [comment]
oops I meant RFC2833 yes. thanks!
